config/routes.rb
Rails.application.routes.draw do
  resources :group_events
  
  namespace :api, defaults: { format: :json }, path: '/api/' do
    namespace :v1 do
      resources :group_events
    end
  end
  
  root 'group_events#index'
end

app/models/group_event.rb
class GroupEvent < ActiveRecord::Base
    scope :active, -> { where(deleted: false) }
end

app/controllers/api/v1/group_events_controller.rb
class Api::V1::GroupEventsController < ApplicationController
  protect_from_forgery with: :null_session
  
  def index
    render json: GroupEvent.active
  end
  
  def show
    render json: GroupEvent.find(params[:id]) 
  end
  
  def create
    event_params = check_params(group_event_params)
    event = GroupEvent.create(event_params)
    if params[:published] == "true" && valid_params?(event_params)
      event.update(published: true)
    end
    render json: event
  end
  
  def update
    event_params = check_params(group_event_params)
    event = GroupEvent.find(params[:id])
    event.update(event_params)
    if params[:published] == "true" && valid_params?(event_params)
      event.update(published: true)
    else
      event.update(published: false)
    end
    render json: event
  end
  
  def destroy 
    event = GroupEvent.find(params[:id])
    event.update(deleted: true)
    render json: event
  end
  
  private
  
  def group_event_params
    params.permit(:name, :location, :start_date, :end_date, :duration)
  end
  
  def check_params(event)
    if event[:start_date].blank? && !event[:duration].blank?
      event[:start_date] = event[:end_date].to_date - event[:duration].to_i.days
    end
    if event[:end_date].blank? && !event[:duration].blank?
      event[:end_date] = event[:start_date].to_date + event[:duration].to_i.days
    end
    if !event[:end_date].blank? && event[:duration].blank? || 
       !event[:start_date].blank? && !event[:end_date].blank? && !event[:duration].blank?
      event[:duration] = (event[:end_date].to_date - event[:start_date].to_date).to_i
    end
    if !event[:start_date].blank? && !event[:end_date].blank? &&
       event[:end_date].to_date < event[:start_date].to_date
       event[:start_date] = ""
       event[:end_date] = ""
       event[:duration] = ""
    end
    event
  end
  
  def valid_params?(event)
    !(event[:name].blank? ||
      event[:location].blank? || 
      event[:start_date].blank? ||
     (event[:end_date].blank? || event[:duration].blank?))
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/group_events_controller.rb
class GroupEventsController < ApplicationController
  def index
    @events = GroupEvent.active
  end
  
  def show
    @group_event = GroupEvent.find(params[:id]) 
  end
  
  def new 
    @group_event = GroupEvent.new                
  end
  
  def create
    event_params = check_params(group_event_params)
    event = GroupEvent.create(event_params)
    if params[:group_event][:published] == "true" && valid_params?(event_params)
      event.update(published: true)
      flash[:success] = "The event was published"
    else
      flash[:warning] = "The event was saved but is not published"
    end
    redirect_to group_event_path(event)
  end
  
  def update
    event_params = check_params(group_event_params)
    event = GroupEvent.find(params[:id])
    event.update(event_params)
    if params[:group_event][:published] == "true" && valid_params?(event_params)
      event.update(published: true)
      flash[:success] = "The event was published"
    else
      event.update(published: false)
      flash[:warning] = "The event was updated but is not published"
    end
    redirect_to group_event_path(event)
  end
  
  def destroy 
    event = GroupEvent.find(params[:id])
    event.update(deleted: true)
    redirect_to group_events_path
  end
  
  private
  
  def group_event_params
    params.require(:group_event).permit(:name, :location, :start_date, 
      :end_date, :duration)
  end
  
  def check_params(event)
    if event[:start_date].blank? && !event[:duration].blank?
      event[:start_date] = event[:end_date].to_date - event[:duration].to_i.days
    end
    if event[:end_date].blank? && !event[:duration].blank?
      event[:end_date] = event[:start_date].to_date + event[:duration].to_i.days
    end
    if !event[:end_date].blank? && event[:duration].blank? || 
       !event[:start_date].blank? && !event[:end_date].blank? && !event[:duration].blank?
      event[:duration] = (event[:end_date].to_date - event[:start_date].to_date).to_i
    end
    if !event[:start_date].blank? && !event[:end_date].blank? &&
       event[:end_date].to_date < event[:start_date].to_date
       event[:start_date] = ""
       event[:end_date] = ""
       event[:duration] = ""
    end
    event
  end
  
  def valid_params?(event)
    !(event[:name].blank? ||
      event[:location].blank? || 
      event[:start_date].blank? ||
     (event[:end_date].blank? || event[:duration].blank?))
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/group_events/index.html.erb
<section>
  <h1 class="h1">Active Events</h1>
  <div>
    <%= link_to new_group_event_path, class:"btn btn-success float-right" do %>
      New
    <% end %>
  </div>
  <div class="table-responsive">
    <table class="table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Location</th>
          <th>Start Date</th>
          <th>End Date</th>
          <th>Duration</th>
          <th>Published</th>
          <th>Delete</th>
        </tr>
      </thead>
      <tbody>
        <% @events.each do |event| %>
          <tr>
            <td><%= event.name %></td>
            <td><%= event.location %></td>
            <td><%= event.start_date %></td>
            <td><%= event.end_date %></td>
            <td><%= event.duration %></td>
            <td><%= event.published %></td>
            <td>
              <%= button_to  "Delete", event, :method => :delete, 
                  class:"btn btn-danger"  %>
            </td>
        <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/group_events/new.html.erb
<h1 class="h1">New Event</h1>
<%= form_for @group_event do |f| %>
  <fieldset class="form-group">
    <label>Name:</label>
    <%= f.text_field :name, { class:"form-control col-md-6", :required => true, 
                              maxlength: 100 } %>
  </fieldset>
  <fieldset class="form-group">
    <label>Location:</label>
    <%= f.text_field :location, { class:"form-control col-md-6", 
                                  maxlength: 100 } %>
  </fieldset>
  <fieldset class="form-group">
    <label>Start Date:</label>
    <%= f.date_field :start_date, { class:"form-control col-md-6" } %>
  </fieldset>
  <fieldset class="form-group">
    <label>End Date:</label>
    <%= f.date_field :end_date, { class:"form-control col-md-6" } %>
  </fieldset>
  <fieldset class="form-group">
    <label>Duration:</label>
    <%= f.number_field :duration, 
        { class:"form-control col-md-6", min: 1, max: 365 } %>
  </fieldset>
  <fieldset class="form-group">
    <label>Do you want to publish?</label>
    <%= f.select(:published,
         options_for_select([["Yes", true],
                             ["No", false]], @group_event.published),
                             { include_blank: "Select an option" },
                             { class:"form-control col-md-6",
                               required: true })  %>
  </fieldset>
  <div>
    <%= f.submit "Save", class:"btn btn-success" %>
  </div>
<% end %>

app/views/group_events/show.html.erb
<% unless @group_event.deleted %>
  <h1 class="h1">
      Event #<%= "#{@group_event.id}"%>
      (<%= "#{@group_event.published ? 'published' : 'draft'}"%>)
  </h1>
  <%= form_for @group_event do |f| %>
    <fieldset class="form-group">
      <label>Name:</label>
      <%= f.text_field :name, { class:"form-control col-md-6", :required => true, 
                                maxlength: 100 } %>
    </fieldset>
    <fieldset class="form-group">
      <label>Location:</label>
      <%= f.text_field :location, { class:"form-control col-md-6", 
                                    maxlength: 100 } %>
    </fieldset>
    <fieldset class="form-group">
      <label>Start Date:</label>
      <%= f.date_field :start_date, { class:"form-control col-md-6" } %>
    </fieldset>
    <fieldset class="form-group">
      <label>End Date:</label>
      <%= f.date_field :end_date, { class:"form-control col-md-6" } %>
    </fieldset>
    <fieldset class="form-group">
      <label>Duration:</label>
      <%= f.number_field :duration, 
          { class:"form-control col-md-6", min: 1, max: 365 } %>
    </fieldset>
    <fieldset class="form-group">
      <label>Do you want to publish?</label>
      <%= f.select(:published,
           options_for_select([["Yes", true],
                               ["No", false]], @group_event.published),
                               { include_blank: "Select an option" },
                               { class:"form-control col-md-6",
                                 required: true })  %>
    </fieldset>
    <div>
      <%= f.submit "Update", class:"btn btn-success" %>
    </div>
  <% end %>
<% else %>
  <h1 class="h1">
      The event #<%= "#{@group_event.id}"%> was deleted
  </h1>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render 'shared/flash_messages' if !flash.empty? %>
  <%= yield %>
</body>
</html>

app/views/shared/_flash_messages.html.erb
<div id="flash_messages">
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, :class => "flash #{key}") %>
  <% end %>
</div>